# Variables
CC = i686-elf-gcc
LD = i686-elf-ld
AS = nasm
QEMU = qemu-system-i386

# Build the kernel
all: os-image.bin

kernel.bin: kernel_entry.o kernel.o
	$(LD) -o $@ -Ttext 0x1000 $^ --oformat binary

kernel_entry.o: kernel_entry.asm
	$(AS) $< -f elf -o $@

kernel.o: kernel.c
	$(CC) -ffreestanding -c $< -o $@

bootsect.bin: boot_sector.asm
	$(AS) $< -f bin -o $@

os-image.bin: bootsect.bin kernel.bin
	copy /b bootsect.bin + kernel.bin os-image.bin

run: os-image.bin
	$(QEMU) -fda $<

clean:
	rm -f *.bin *.o *.dis

